title: 琳琳的博客
email: "linlinblogs@sina.com"
description: "记录工作和生活中学习或复习的知识。"
baseurl: "/"
url: "https://study.iamlinlin.fun"
twitter_username: "linlin"
github_username:  "linlin"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 10
paginate_path: "/page/:num"
